### ISSUE TITLE
Using pandas `display.max_columns` breaks itables

### ISSUE THREAD

**Issue by artdgn** [mwouts/itables#14]
When pandas option `display.max_columns` is set to None, trying to use `show()` results in:

```TypeError: '>' not supported between instances of 'int' and 'NoneType'```

It seems to be because of [this line](https://github.com/mwouts/itables/blob/2617bed0829ae8b52ea4543cbddcfc77a0ac663a/itables/javascript.py#L75) and then later using that `None` in [this line](https://github.com/mwouts/itables/blob/2617bed0829ae8b52ea4543cbddcfc77a0ac663a/itables/downsample.py#L38). 

I'd submit a PR, but it doesn't look like this package is actively maintained. Otherwise it's a simple change of setting the default unless it's None.

## Workaround:
Pass `maxColumns` explicitly to `show()`

**Comment by mwouts** [comment]
Hi @artdgn , thank you for reporting this.
Indeed it has been a long time since we made the last release.
But I'll be happy to make a new one !
So please proceed if you wish to make a PR.
