### ISSUE TITLE
Table does not display text correctly in VS code 

### ISSUE THREAD

**Issue by Serbernari** [mwouts/itables#156]
![image](https://user-images.githubusercontent.com/30036289/215763037-7ef0aeeb-5e80-4004-bc87-ce431447eba0.png)
For some reason in VS code on my Ubunry 18.0 only rare lines get displayed. I tried to change maximum output length but it did not help

**Comment by mwouts** [comment]
Hello, can you please share which version of `itables` you are using? This reminds me of issues we had in previous versions, see e.g. #103 .

**Comment by Serbernari** [comment]
Sorry for slow answer, it's '1.4.6' installed from pip

**Comment by TiPPeX2** [comment]
I also see the same behaviour in JupyterLab 
Successfully installed itables-1.5.2
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/8648360/230889782-76c21287-8c6e-44f2-8e11-a6b17871fbdb.png">

**Comment by vvilhonen** [comment]
Same problem on itables 1.6.1, vscode 1.82.3, ms-toolsai.jupyter v2023.8.1002501831
