### ISSUE TITLE
Example with images

### ISSUE THREAD

**Issue by avivajpeyi** [mwouts/itables#158]
Is it possible to use itables to generate a table with images? Eg: 

https://datatables.net/examples/basic_init/data_rendering.html
<img width="880" alt="Screen Shot 2023-03-08 at 10 34 42 am" src="https://user-images.githubusercontent.com/15642823/223558166-f5a25c9d-02da-4e5b-9c62-a523b4a09452.png">

**Comment by avivajpeyi** [comment]
Seems it is as easy as: 

```python
import pandas as pd
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)

IMAGE = "<img src='https://duckduckgo.com/assets/logo_homepage.normal.v108.svg'/>"
row = ["Ducky", 12, IMAGE]
df = pd.DataFrame([row for _ in range(5)], columns = ['Name', 'Age', 'Picture'])

df
```
<img width="528" alt="Screen Shot 2023-03-08 at 11 38 41 am" src="https://user-images.githubusercontent.com/15642823/223570080-c818fd71-957b-4f27-b254-d475bba8390c.png">

**Comment by mwouts** [comment]
Yes that's right -  HTML within the table is supported so you can use the `<img src="...">` approach. That's a great question by the way, I will add an example for this in the documentation - thanks for asking!

**Comment by mwouts** [comment]
This is now documented at https://mwouts.github.io/itables/advanced_parameters.html#images-in-cells.
You can either use an image url or a base64 encoding (see the documentation link).

And the sample country df used in the documentation now has flags - the URLs are generated here:
https://github.com/mwouts/itables/blob/872a7dd1c2bb8fb4380ff41ffa38a86a8a5b5743/itables/sample_dfs.py#L51-L56

Very good question, thank you again for asking!
