### ISSUE TITLE
how to highlight table row based on value in a column

### ISSUE THREAD

**Issue by sandsmichael** [mwouts/itables#176]
Is it possible to highlight a row if a column in that row contains a certain value? I have similarly tried to change the font color for negative values (which works) but changing the background-color for a row does not appear to. Are there any examples of this in the documentation?

**Comment by mwouts** [comment]
Are you looking for something like this?
```
from itables import show, JavascriptFunction
import pandas as pd


show(
    pd.DataFrame([[-1, 2, -3, 4, -5], [6, -7, 8, -9, 10]], columns=list("abcde")),
    columnDefs=[
        {
            "targets": "_all",
            "createdCell": JavascriptFunction(
                """
function (td, cellData, rowData, row, col) {
    if (rowData.some((x) => x < 0)) {
        $(td).css('background-color', 'red')
    }
}
"""
            ),
        }
    ],
)
```
which gives
![image](https://user-images.githubusercontent.com/29915202/231978954-df73a209-d3ce-49a8-9b4e-b065423cdf33.png)

With respect to the [color example](https://mwouts.github.io/itables/advanced_parameters.html#advanced-cell-formatting-with-js-callbacks) I have changed
- `$(td).css('color', 'red')` to `$(td).css('background-color', 'red')`
- and the condition `cellData < 0` to `rowData.some((x) => x < 0)`

I agree that this is quite complicated, and also having to recur to Javascript is not very user friendly for Python users. Is that something that you have done before in the default representation of Pandas ? Can you share how you would have done it there ?

**Comment by sandsmichael** [comment]
As far as the javascript approach goes, I was thinking there might be a way to make use of the rowCallback function.  It would be ideal if this logic could be passed into the show function through python and have the javascript styling applied behind the scenes. The link below shows use of the rowCallback (applied only to one column).
https://datatables.net/examples/advanced_init/row_callback.html

I've made use of pandas style method in order to apply this formatting in Jupyter before.

`import pandas as pd

def highlight_row_by_value(s, value, column, color):
    data = pd.Series(data=False, index=s.index)
    data[column] = s.loc[column] == value
    return [f'background-color: {color}' if data.any() else '' for v in data]

def positive_negative(cell):
    if type(cell) != str and cell < 0 :
        return 'color: red'
    else:
        return 'color: black'
        
df = pd.DataFrame([[-1, 2, -3, 4, -5], [6, -7, 8, -9, 10]], columns=list("abcde"))

display(
    df.style.applymap(positive_negative).apply(highlight_row_by_value,  value=6, column = 'a', color = 'yellow', axis=1)
    )`

**Comment by mwouts** [comment]
Thanks @sandsmichael for sharing the `style` example! I will have a look and think about this.

You can use `createdRow` as well, below is an example:
```
from itables import show, JavascriptFunction
import pandas as pd
import itables.options as opt

opt.css = opt.css + """
td.highlight {
        font-weight: bold;
        color: blue;
    }"""

show(
    pd.DataFrame([[-1, 2, -3, 4, -5], [6, -7, 8, -9, 10]], columns=list("abcde")),
    createdRow = JavascriptFunction("""function (row, data, index) {
            if (data[2]<0) {
                $('td', row).addClass('highlight');
            }
        }
""")
)
```
which gives this:
![image](https://user-images.githubusercontent.com/29915202/232208707-e7a5275d-fc18-45b1-9c95-4c61df079dda.png)
