### ISSUE TITLE
Databricks support?

### ISSUE THREAD

**Issue by Ljupch0** [mwouts/itables#186]
I understand that it's not among the supported editors, but would be a very cool display option. The standard df view of pandas leaves much to be desired.

Currently I am getting this when displaying a table:
`Uncaught ReferenceError: $ is not defined`

**Comment by mwouts** [comment]
Hey @Ljupch0 , thank you for reporting this. I don't have access to databricks so it might be a bit challenging for me to do anything about this, but let me ask you two quick questions anyway...

1. Could you give a try to both the offline and connected mode? I mean, call `init_notebook_mode(all_interactive=True, connected=True/False)` and rerun all your notebook?
2. Are you aware of any interactive library that works in databricks? Like `plotly` or Jupyter Widgets?
