### ISSUE TITLE
Acknowledging itables

### ISSUE THREAD

**Issue by avivajpeyi** [mwouts/itables#188]
Is there a specific way users should acknowledge itables? 
I added a caption [in my table](https://cjhaster.com/NRSurrogateCatalog/events/gw_menu_page.html) with a link to itables (and datatables) but not sure if you'd like something else.

**Comment by mwouts** [comment]
Thanks @avivajpeyi for suggesting this! There is no obligation whatsoever but that's very kind of you. I have added a word on this at https://mwouts.github.io/itables/contributing.html.
