### ISSUE TITLE
Rangeindex index not displayed

### ISSUE THREAD

**Issue by nathaniel** [mwouts/itables#190]
If I create a DataFrame without explicitly giving it an index, it automatically gets an integer index. That index column is displayed when printing, or via Jupyter's default pretty display of DataFrames. But itables interactive notebook mode doesn't show that column.

It would be good for itables to display that default index column, since it's part of the DataFrame (when writing it to CSV, for example); or at least include an option to allow it to be displayed.

Great package!

**Comment by mwouts** [comment]
Hey @nathaniel , great question, thank you!

By default the index is not shown when it is equal to the default index (i.e.: range index, no name).

This behavior is governed by the [`showIndex` argument/option](https://github.com/mwouts/itables/blob/b4c447383c5b97c9555b90bf1bcd7ceee327dea3/itables/options.py#L8-L10). As it was not documented, I have prepared a PR #191 to document it, can you have a look at let me know whether the option addresses your point?

**Comment by nathaniel** [comment]
Marc, that's perfect, addresses my issue wonderfully!

Thanks for documenting -- I had hunted around a bit before posting the
issue, including reviewing Advanced parameters.

Nathaniel
