### ISSUE TITLE
Set Advanced Parameters as Global Options

### ISSUE THREAD

**Issue by daniel-fink** [mwouts/itables#204]
Some parameters (e.g. scrollX, Column width, etc -- not an exhaustive list) do not seem to be available as global options.
Is there a way to make them so?

**Comment by mwouts** [comment]
Hi Daniel, thanks for asking.

My expectation is that you should be able to set these options on 'opt' as for the other global options (after 'import itables.options as opt').

Let me know if that works for you.

**Comment by daniel-fink** [comment]
Thanks Marc

I'm not sure what you mean by 'setting them on `opt`' as syntax.
e.g. `opt(scrollY='450px', scrollX=True, scrollCollapse=True, paging=False)` returns an error as it is not callable.

Could you give an example of what you mean?

Thanks

**Comment by mwouts** [comment]
I will come back with an example later on, but I expect that you should be able to set them in the same way we set 'style' in this paragraph: https://mwouts.github.io/itables/advanced_parameters.html#position-and-width

**Comment by daniel-fink** [comment]
Hi Marc. I haven't been able to find syntax that works; do those advanced parameters sit in the `opt.style` property with css-esque syntax (e.g. opt.style = "table-layout:auto;width:auto;scrollX:true"?) Do you have an example?

**Comment by mwouts** [comment]
Hi @daniel-fink , excuse me, I completely forgot to provide an example.

This is what I meant:
```
from itables import init_notebook_mode
import itables.options as opt

# Set these parameters as defaults in itables.show
opt.scrollY='450px'
opt.scrollX=True
opt.scrollCollapse=True
opt.paging=False

init_notebook_mode(all_interactive=True)
```
and then e.g.
```
from itables.sample_dfs import generate_random_df

df = generate_random_df(rows=100, columns=100)
df
```
will use these parameters:
![image](https://github.com/mwouts/itables/assets/29915202/ffa3f287-d6a8-4d22-8c76-649c1a49ee1a)

I think this is what you wanted right?
