### ISSUE TITLE
A bug in displaying sorted tables

### ISSUE THREAD

**Issue by pipme** [mwouts/itables#205]
Hi,

Thanks for developing this nice package! There seems to be a bug when displaying a sorted table. The largest number of the column `A` is not displayed after sorting according to `A`. To reproduce: 

```python
import pandas as pd
from itables import init_notebook_mode

init_notebook_mode(all_interactive=True)
pd.read_csv('data.csv')
```
[data.csv](https://github.com/mwouts/itables/files/13320257/data.csv)

(The largest value should be `36.5` while after sorting it displays the second largest one `-15.17` in the first row)

**Comment by mwouts** [comment]
Hi, thanks for reaching out! Is there any mention of the table being downsampled, at the bottom left of the interactive table? In that case only a subset of the data is displayed, hence what you see on the maximum.

See also https://mwouts.github.io/itables/downsampling.html

**Comment by pipme** [comment]
Ah yes, you are right. I didn't see the notice that it's subsampled. After `import itables.options as opt; 
opt.maxBytes = 0` it's alright. Thanks!

**Comment by mwouts** [comment]
Glad it worked! Note that you might want to be careful with the size of the tables if you completely deactivate the downsampling. Large tables might make your notebook very big and/or unresponsive (since the full table data is injected in the html representation of the notebook).
