### ISSUE TITLE
Immobilizing columns

### ISSUE THREAD

**Issue by CarlaFernandez** [mwouts/itables#207]
Hello,
I was wondering if there is any way to immobilize certain columns or the header from the rendered itable, just as you can do in Excel.
It would be really useful to visualize a large dataframe.
Thank you!

**Comment by mwouts** [comment]
Hello @CarlaFernandez , thanks for asking!

Well `datatables.net`, the javascript library that provides the interactivity, does have support for the fixed columns, cf. https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html

Unfortunately these fixed columns are provided through the `fixedcolumns` extension, and at the moment `itables` does not have support for the extensions.

I don't have plans to add support for these in the near future, but nevertheless please this issue open, it might come at some point!

**Comment by mwouts** [comment]
This is now possible with `itables==2.0`! See the example here: https://mwouts.github.io/itables/extensions.html#fixedcolumns
