### ISSUE TITLE
Center Align Table

### ISSUE THREAD

**Issue by jatin-sandhuria** [mwouts/itables#22]
How do I center align the header and the rows within the table ? I have tried many things but nothing seems to be working.

**Comment by mwouts** [comment]
Hi I'll add one example to the README:

> You can use the datatables.net [cell classes](https://datatables.net/manual/styling/classes#Cell-classes) like `dt-left`, `dt-center`, `dt-right` etc to set the cell alignment. Specify it for one table by using the `columnDefs` argument of `show`

```python
show(df, columnDefs=[{"className":"dt-center",  "targets": "_all"}])
```

> or globally by setting `opt.columnDefs`:

```python
opt.columnDefs = [{"className":"dt-center", "targets": "_all"}]
df
```
