### ISSUE TITLE
limit rows per page

### ISSUE THREAD

**Issue by micboat** [mwouts/itables#228]
Using pagesize, is there a way to limit the number of rows displayed per page, say 10 rows per page. Just cant find anything in the docs for that

**Comment by mwouts** [comment]
Hi @micboat , thanks for reaching out. I am not sure what you mean by `pagesize`. Could you share an example?

Have you tried the `lengthMenu` argument, see e.g. https://mwouts.github.io/itables/advanced_parameters.html#how-many-rows-per-page ?

**Comment by micboat** [comment]
Awesome, that worked! `lengthMenu` was exactly what I was looking for. Thanks a lot
