### ISSUE TITLE
1.7.0 removes default grid styling present in < 1.7.0

### ISSUE THREAD

**Issue by cpcloud** [mwouts/itables#229]
Here's a rendered table from a local build of the Ibis website's operation support matrix (https://ibis-project.org/support_matrix) using 1.6.4:
![image](https://github.com/mwouts/itables/assets/417981/f01fc3f9-68ab-4bea-af48-f94c9f8a84e8)

With 1.7.0:

![image](https://github.com/mwouts/itables/assets/417981/8b9aaf12-7e17-4680-8a94-9b00ab3df3ea)

**Comment by mwouts** [comment]
Do you think this might be caused by the move of the style inside the div?

![image](https://github.com/mwouts/itables/assets/29915202/33e41775-a8be-43fc-ad8f-e12dfc7bbb30)

Cf. https://github.com/mwouts/itables/compare/v1.6.4...v1.7.0

If I were to revert this change in a branch, would you be able to install it locally for testing?

**Comment by cpcloud** [comment]
Yep, I can give it a try locally

**Comment by mwouts** [comment]
Ok great! Can you try this version then?
```
pip install git+https://github.com/mwouts/itables.git@revert_style
```
Thanks

**Comment by mwouts** [comment]
Hey @cpcloud , have you been able to give a try at the above? Thanks!

**Comment by cpcloud** [comment]
Yep, unfortunately it didn't seem to help.

**Comment by mwouts** [comment]
I see. Do you think you could share a minimal example that I could run on my end?

**Comment by mwouts** [comment]
Hi @cpcloud , would you mind giving a try at `itables==2.0`? I'd be curious to know if the issue is resolved now.

**Comment by cpcloud** [comment]
@mwouts Looks good with `itables==2.0`! Thanks!

![image](https://github.com/mwouts/itables/assets/417981/d9a4c8e1-28d2-47b4-b86c-da85a4f494f9)

**Comment by mwouts** [comment]
Awesome! Thanks for letting me know!
