### ISSUE TITLE
Unreadable text in dark mode

### ISSUE THREAD

**Issue by safranchik** [mwouts/itables#232]
Hi Marc,

I was using itables and when I switched to dark mode, the `entries` and `search` headers became illegible as they retained dark letters. Here's an example of what it looks like.

![image](https://github.com/mwouts/itables/assets/23159096/14493df7-21e5-406d-b9f6-195f583f522a)

Love the library - keep up the amazing work!

**Comment by mwouts** [comment]
Hey @safranchik , can you give a try to this development version?
```
pip install git+https://github.com/mwouts/itables.git@fix_dark_mode_in_vscode
```
Let me know how it goes. Thanks
