### ISSUE TITLE
How to wrap content in the cell ? 

### ISSUE THREAD

**Issue by CavemanWork** [mwouts/itables#24]
Version:
itables==0.3.0

Code:
```
import itables
import itables.options as opt
opt.classes = ["display", "cell-border"]
opt.maxBytes = 2**20
itables.show(
    bg_all_df, scrollY="800px", scrollCollapse=True, paging=False
)
```

Issue:
If the text lenght larger than threshold if found that the tail will cutdown. 
how to show the full centent in the cell without wrap?

**Comment by CavemanWork** [comment]
Any update ?

**Comment by mwouts** [comment]
Hi @CavemanWork , well below are some experiments, please let me know if any of them is close to what you want to do...

If we do
```python
import itables
import itables.options as opt
import pandas as pd

opt.maxBytes = 2**20
bg_all_df = pd.DataFrame({"text":["long " * 128 + "text"]})

opt.classes = ["display", "cell-border"]
itables.show(
    bg_all_df
)
```
the cell content is wrapped
![image](https://user-images.githubusercontent.com/29915202/122985468-85527800-d39e-11eb-89be-8997ed743b52.png)

Now if we do
```
opt.classes = ["display", "nowrap"]
itables.show(bg_all_df)
```
then it appears truncated:
![image](https://user-images.githubusercontent.com/29915202/122985627-b3d05300-d39e-11eb-9bb2-21a489746aa6.png)

And finally if we set a custom width (but I don't know how to set the width automatically, maybe you can ask at https://datatables.net ?) we can scroll horizontally:
```
itables.show(bg_all_df,  columnDefs=[{"width": "4000px", "targets": "_all"}])
```
![image](https://user-images.githubusercontent.com/29915202/122985788-e0846a80-d39e-11eb-9dce-7a38ba58ce82.png)

Hope that helps!
