### ISSUE TITLE
Is there a way to specify which column is initially sorted ...

### ISSUE THREAD

**Issue by brianminsk** [mwouts/itables#25]
... for example, if I want the table to initially appear reverse sorted on the 2nd column?

**Comment by mwouts** [comment]
Hi @brianminsk , well the [`order`](https://datatables.net/reference/option/order) argument from `datatable.net` seems to work nicely:

![image](https://user-images.githubusercontent.com/29915202/122986602-efb7e800-d39f-11eb-9a7d-2557808b2bb7.png)

**Comment by brianminsk** [comment]
Great, thank you very much. I'm new to iTables and didn't understand that I could use DataTables options.

**Comment by mwouts** [comment]
You're welcome! Thanks for asking BTW - I'm sure that having this issue documented will help someone else!
