### ISSUE TITLE
UnicodeDecodeError in JupyterLab Desktop

### ISSUE THREAD

**Issue by apogorzelska** [mwouts/itables#252]
I'm getting following error in [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop). I'm using a conda environment with Python 3.11.8 on Windows 11, itables version 2.0.0 installed from conda-forge.

![image](https://github.com/mwouts/itables/assets/7746851/0e751547-08c7-414b-ac43-0c1b5ad6a777)

**Comment by mwouts** [comment]
Thank you @apogorzelska for reporting this! Oh sorry I had not tested `itables` on Windows yet, I should have thought of this. I plan to look into this in the coming days.

Meanwhile, may I ask you if `init_notebook_mode(all_interactive=True, connected=True)` works any better?

**Comment by mwouts** [comment]
Just gived it a try, and it worked in an environment created with
```
conda create -n test_itables 'itables==2.0' jupyterlab -c conda-forge
```

![image](https://github.com/mwouts/itables/assets/29915202/a147ed3e-d5b9-4f68-83cc-2dc6e197c4a9)

For some reason `utf-8` does not seem to be the default on your installation, I will prepare a PR for using an explicit encoding argument.

**Comment by mwouts** [comment]
The PR and the instructions to test it are available [here](https://github.com/mwouts/itables/pull/253#issuecomment-2028059053). Can you let me know if that fixes this issue? You might have to install `nodejs` in your conda environment. Thanks!
