### ISSUE TITLE
Modernize paging buttons style

### ISSUE THREAD

**Issue by planetoryd** [mwouts/itables#256]
```python
from IPython import display
from itables import init_notebook_mode, show, options

init_notebook_mode(all_interactive=True)

css = """
div.dt-container .dt-paging .dt-paging-button:hover {
    background: grey
}
div.dt-container .dt-paging .dt-paging-button.current {
    background: none
}
"""
display.display(display.HTML(f"<style>{css}</style>" ""))

```

The linear gradient was killing me

![image](https://github.com/mwouts/itables/assets/68096727/444806aa-0998-4cf8-b82b-ce4608a9450c)

**Comment by mwouts** [comment]
Thanks @planetoryd for sharing! If you don't mind I will continue to take the default CSS from `datatables.net`, but it's great to know how to change it.
