### ISSUE TITLE
itable doesn't work on Colab

### ISSUE THREAD

**Issue by ofir-reich** [mwouts/itables#26]
Just prints out an empty table. Is this a known issue?
I'm using Google Colaboratory with a local runtime, i.e. running my own Jupyter backend, not hosted by Google.

**Comment by mwouts** [comment]
Hello @ofir-reich , well sorry indeed `itables` imports a javascript library (datatables.net) and this is known to work only in Jupyter notebook. 

Still, there might be a chance that the workaround for JupyterLab also works for Colab. Would you like to give a try to [this code snippet](https://github.com/mwouts/itables/issues/3#issuecomment-688330386) and report whether it works or not? Thanks

**Comment by ofir-reich** [comment]
Thanks for the quick response!
I tried and unfortunately that code snippet doesn't work. I'm still getting an empty table printed out - with only the column names (as before).

**Comment by mwouts** [comment]
The current development version of `itables==0.4.0-dev` does work now on Colab, following #43:
![image](https://user-images.githubusercontent.com/29915202/148451755-6bf635ce-769a-4686-a235-28fd7151e4f3.png)
