### ISSUE TITLE
New landing page for conda forge `itables`

### ISSUE THREAD

**Issue by Anselmoo** [mwouts/itables#279]
It may be an idea to set the link to the GitHub repo https://github.com/conda-forge/itables-feedstock because:

1. The user always sees if the latest version was a successful build
2. Can easily see what the latest version is
3. Can easier find a way to contribute

https://github.com/mwouts/itables/blob/1238f9c3e32b92990bfeca749dcac4a8930f205f/README.md?plain=1#L6

**Comment by mwouts** [comment]
Hi @Anselmoo , sure that would be better, thanks!

By the way I don't see yet the new version (2.1.0) on conda, do I need to do something to trigger a new build?

**Comment by Anselmoo** [comment]
That is something that I am aware of; in this particular case the bot misses the latest release, I had to correct it manually several times.

One thing to consider is activating the [auto-merge feature](https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-bot-automerge) of conda forge. To do this, simply create an issue with the following title:

* __conda-forge-admin, please add bot automerge__

and this makes:

```yaml
bot:
  automerge: true
```
like [here](https://github.com/conda-forge/spectrafit-feedstock/blob/main/conda-forge.yml#L5-L6)

**Comment by mwouts** [comment]
Thanks @Anselmoo! In the end the conda package was automatically released in the hour after I reached out to you (but maybe 8 hours after the pypi release). And thanks for the hint too!

**Comment by mwouts** [comment]
Hi @Anselmoo , if you don't mind I will keep the current link, now that we have added a description the conda package looks nicer! Thanks
