### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by johann-petrak** [mwouts/itables#29]
Shows only the header line for a dataframe. 

Using itables 0.3.0 in a jupyter notebook 

```
IPython          : 7.28.0
ipykernel        : 6.4.1
ipywidgets       : not installed
jupyter_client   : 7.0.6
jupyter_core     : 4.8.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : not installed
nbconvert        : not installed
nbformat         : not installed
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.1.0
```

**Comment by schwabts** [comment]
Using itables was not straighforward for me either. In the end it was helpful to follow

[https://mwouts.github.io/itables/](https://mwouts.github.io/itables/)

which  - for getting started - comes down to
```
!pip install itables
!pip install world_bank_data

from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)
import world_bank_data as wb

df = wb.get_countries()
df
```

**Comment by mwouts** [comment]
Well, I think there are significant chances that version 0.4.0 (to be released soon) will work better. If not, would you mind opening a new issue? I'll also need to see the browser logs. Thanks
