### ISSUE TITLE
SearchBuilder picks up &nbsp as column name for Pandas styler object but works fine for Pandas dataframe object

### ISSUE THREAD

**Issue by sherry151** [mwouts/itables#297]
```
    from itables import init_notebook_mode
    import itables.options as it_opt
    init_notebook_mode(all_interactive=True)
    it_opt.paging = False
    it_opt.scrollY = "50vh"
    it_opt.scrollCollapse = True
    it_opt.scrollX = True
    it_opt.keys = True
    it_opt.select = True
    it_opt.buttons =   ["csvHtml5", "excelHtml5",
                        {
                           "extend": "colvis",
                           "collectionLayout": "fixed columns",
                           "popoverTitle": "Column visibility control"
                        }
                    ]
    it_opt.layout={"top1": "searchBuilder", "topEnd": None}
    it_opt.column_filters="footer"
```

This works fine with a DataFrame object even when the dataframe has a multiindex. But it does not work with a styler object for the same multiindex dataframe

**DataFrame**
<img width="425" alt="image" src="https://github.com/mwouts/itables/assets/4744615/49436079-5d5f-425e-8d55-b61f0f962a95">

**Styler**
<img width="414" alt="image" src="https://github.com/mwouts/itables/assets/4744615/aee16ad4-cb7e-49ef-b5e8-d058eed8df0d">

**Comment by mwouts** [comment]
I guess you will have to set custom names for your columns using https://datatables.net/reference/option/columns.searchBuilderTitle

**Comment by sherry151** [comment]
This worked beautifully. Thank you.
