### ISSUE TITLE
Overflow-x not working properly within an ipywidget.Output widget

### ISSUE THREAD

**Issue by c3-yiminliu** [mwouts/itables#302]
See the following example:
```
import pandas as pd

import itables.options as opt
from itables import init_notebook_mode, show
from itables.sample_dfs import get_countries

df = get_countries(html=False)

df = pd.concat([df]*10, axis=1)

init_notebook_mode(all_interactive=True)
```

```
show(df)
```
<img width="1382" alt="image" src="https://github.com/mwouts/itables/assets/73711778/c348766c-6182-4cce-8478-b74272265bfc">

Dataframe displays nicely in a cell. X-scroll is available, pages, search box are visible.

```
import ipywidgets
out = ipywidgets.Output()

with out:
    show(df)

out
```

When displayed within an ipywidgets.Output, X-scroll is not available, pages, search box are not visible.

<img width="1369" alt="image" src="https://github.com/mwouts/itables/assets/73711778/ad49706e-13b1-4d9d-ba67-ff9c7cd50656">

Maximize the window does not help since there are too many columns:
<img width="2853" alt="image" src="https://github.com/mwouts/itables/assets/73711778/d350b10b-6c13-40ca-8fd3-4973ecf826cf">

Need to zoom out by a lot to see the pages and search box.

<img width="2967" alt="image" src="https://github.com/mwouts/itables/assets/73711778/c65b2246-d30d-44a2-be32-0ea26912fe5e">

Is there a way to improve the display within an ipywidgets.Output? 

Thanks

**Comment by mwouts** [comment]
Hi @c3-yiminliu, thanks for sharing this example, I didn't know that you could use ITables in an output widget! That's great!

What version of Jupyter/ITables are you using? When I run your example it looks fine on my end (Jupyter Lab 4.0.11). FYI the horizontal overflow was fixed in ITables v2.1.2, see https://mwouts.github.io/itables/changelog.html
![image](https://github.com/mwouts/itables/assets/29915202/2df8c731-4f45-4c48-b6fd-5bbe043e43a2)

Also, I plan to provide a Jupyter widget for ITables soon, you might want to subscribe to #267 for updates.

**Comment by c3-yiminliu** [comment]
Hi @mwouts , thanks for the reply!

This is my Jupyter and itables version:
<img width="386" alt="image" src="https://github.com/mwouts/itables/assets/73711778/cff34b1a-76d1-41a7-b90a-a03faa735717">

In your example, are you able to see all the columns? In this example, the dataframe has 50 columns.

**Comment by mwouts** [comment]
I think so! Well I mean I can scroll horizontally, cf. the screencast below. So maybe this is an incompatibility with Jupyter 3? Also, I am using `ipywidgets==8.1.3`
![itables_in_output_widget](https://github.com/mwouts/itables/assets/29915202/d818853a-455f-4750-9be7-1248f90f1331)

**Comment by c3-yiminliu** [comment]
Thanks @mwouts. Good to know it works well with Jupyter 4. 

My ipywidgets version is 
<img width="225" alt="image" src="https://github.com/mwouts/itables/assets/73711778/2bc16129-0ddd-4f5a-9b71-7f37e5514389">

One "workaround" is to provide a fixed width in pixels. This does not work well for all screen resolutions but at least can be configured.
<img width="1035" alt="image" src="https://github.com/mwouts/itables/assets/73711778/4f2ba1bb-7581-4648-98d5-7f7757147600">

Thanks for the help!

**Comment by c3-yiminliu** [comment]
@mwouts feel free to close the issue (given it works well with latest Jupyter).
