### ISSUE TITLE
Missing `conneted=False` and `dt_bundle` support in `to_html_datatable`

### ISSUE THREAD

**Issue by matthieucx** [mwouts/itables#306]
Hello ! Thanks for the very neat tool.

## Issue

HTML webpages using a Datatable generated with `to_html_datatable` while passing `connected=False` hangs indefinitely, as they don't seem to have the required ressources.

Additionally (and I guess as a result) you cannot seem to pass `dt_bundle` to `to_html_datatable`, as it's treated as a kwargs, while `dt_url` seems to be handled.

## To reproduce

Sample Python file:

```python
import pandas as pd
from jinja2 import Environment, FileSystemLoader
from itables import to_html_datatable

def export_html(data: pd.DataFrame) -> None:
	# Set up Jinja2 environment
	env = Environment(loader=FileSystemLoader("."))
	template = env.get_template("template.html")

	# Generate HTML content
	html_content = template.render(data=data)

	with open("output.html", "w") as f:
		f.write(html_content)
		

if __name__ == "__main__":

	df = pd.DataFrame({
		'A': [1, 2, 3, 4],
        'B': [5, 6, 7, 8],
        'C': [9, 10, 11, 12]
    })
	
	html = to_html_datatable(
		df,
		connected=True,
	)
	export_html(data=html)
```

HTML template:

```html
<!DOCTYPE html>
<html>
    <body>
        {{ data }}
    </body>
</html>
```

Run the Python file and open the generated webpage.

## Context

I am trying to share a small CSV in the most barebone way, while still having it interractive. I have found your tool perfect for that, in particular the `to_html_datatable` method.

I have particularly long texts and want to use the [DataTables Ellipsis plugin](https://datatables.net/plug-ins/dataRender/ellipsis). I followed your [instructions in the docs](https://mwouts.github.io/itables/custom_extensions.html) and created a custom `dt_bundle`. I can't seem to use it.

I may have missed something, in which case I apologize, and would love to receive a pointer as to what may be happening here.

Thanks!

**Comment by mwouts** [comment]
Hi @matthieucx , thanks for reaching out! I'm glad that you were able to follow the instructions to use custom extensions!

Can you deploy the two files (`dt_bundle.js` and `dt_bundle.css`) from the bundle to your server, and set `dt_url` to the path to the `dt_bundle.js` file? And keep using `connected=True`?

Note that it should be possible to use `connected=False` (e.g. if you want to generate a standalone html file), but that's probably a bit more complicated - essentially you would need to include the output of `init_notebook_mode` (which displays the custom bundle) in your html file.

**Comment by matthieucx** [comment]
Hi @mwouts, thank you for the quick response and the pointers!

I am okay with deploying the files. I did so through Python's built-in HTTP server, but I feel like I am missing something. Whether using my custom dt_bundle, building it from source without modifications or downloading the one from the original `DT_URL_*`, the site hangs indefinitely. The page works fine when using your base `dt_url`.

I am sure I have the right URL, as I can see files served in the server logs (`GET /dt_bundle.js HTTP/1.1" 200`). Do you have any idea of what might be happening here?

Thanks for the clarification on `connected=False`!

**Comment by matthieucx** [comment]
I packaged my custom bundle on NPM and used UNPKG to fetch the bundle, as you do in itables. Works perfectly. I do not have prior experience with JS and NPM, but your documentation sent me in right direction. Thanks for your help!

**Comment by mwouts** [comment]
Great!

Not sure that matters now, but it's unexpected that the server approach did not work - do you think this could have been a permission issue?
