### ISSUE TITLE
issue with conversion of notebook to pdf 

### ISSUE THREAD

**Issue by pali07** [mwouts/itables#307]
Hi ,
i want to convert the jupyter notebook into pdf format. I am using  `jupyter nbconvert --to pdf notebook.ipynb` command. 
I want to display the whole table but it is not displaying.
![image](https://github.com/user-attachments/assets/26c870f4-a8e0-4343-b75a-170f6ffe89a4)
Can you please help me with this ?

I want to convert to pdf because i want to export the whole output of the specific cell in the jupyter notebook? Or is there any way to do this without converting to pdf 
Thanks for the helping....

**Comment by mwouts** [comment]
Hi @pali07 , well PDF is not a natural output format for ITables - remember that ITables is a wrapper for https://datatables.net/, a javascript library. Can you use HTML instead?

You can export the full notebook to HTML with `jupyter nbconvert --to html`.

Alternatively, if you are looking to export just one table to HTML, you can use [`to_html_datatable`](https://mwouts.github.io/itables/html_export.html).

**Comment by pali07** [comment]
Thank you @mwouts for the quick response. I will use html format for my use case
