### ISSUE TITLE
Jupyter Notebook 7 + itables → unreadable table

### ISSUE THREAD

**Issue by MichalRIcar** [mwouts/itables#312]
Hello, 

I am using itables 2.1.4 in JN 7.2.1 and when output is generated it occasionally "destroys" itables view.  
It happens only if I am not "watching" the generated output (say I am at the top of JN and output is being generated below my screen view).

I suspect that issue might be rather on JN side, but posting here first as it happens mainly to itables. 
Although plotly is affected by some shrinkage too - when not watching output directly and rather scroll there after it was generated, plotly graph is shrinked (but it can be fixed by clicking on Autoscale on plotly graph).

Please let me know how I can support the issue with more data, views or video or anything which makes the cause more clear.

![image](https://github.com/user-attachments/assets/2f9d8792-455f-41e5-9888-86359110df25)

**Comment by mwouts** [comment]
Hi @MichalRIcar , thank you for reporting this!

Yes I am interested in knowing a bit more about this. I gave it a quick try, opening the [sample_dataframes.md](https://github.com/mwouts/itables/blob/main/docs/sample_dataframes.md) notebook in Jupyter Notebook (7.0.8) and I made sure the tables were creating without being visible, but so far I could not reproduce the issue on my end.

@AllanJard would you have an idea of what might cause the table to look like the screenshot above? Thanks!

**Comment by AllanJard** [comment]
That's fairly catastrophic isn't it! Almost certainly a CSS issue that a test case would be needed for to be able to inspect the CSS.

[I could get something a little like that](https://live.datatables.net/qutejehe/1/edit) with some dodgy CSS.

**Comment by mwouts** [comment]
Thank you @AllanJard for the hint! I know what to look for now, thanks!

@MichalRIcar I have the following questions for you:
- Does the problem persist when you export the notebook to html (file / save and export notebook as html)? If so, can you email me one such html file - that would help a lot!
- Do you still have the `init_notebook_mode` cell when the problem occurs? (that's the cell that injects the css, however I see in Allan's example that the problem can occur with the datatable css)? Do you use the offline mode (default) or the connected mode?

**Comment by mwouts** [comment]
Thanks @MichalRIcar for the additional info! The default value of the `style` option is `table-layout:auto;width:auto;margin:auto;caption-side:bottom`, you might want to keep the other values.

See also https://github.com/mwouts/itables/blob/main/src/itables/options.py#L25-L34

and https://mwouts.github.io/itables/custom_css.html#position-and-width
