### ISSUE TITLE
DataTables warning with Quarto and Pandas Styler

### ISSUE THREAD

**Issue by SvenKlaassen** [mwouts/itables#317]
When using pandas style with quarto, the html files display the following DataTables warning.

```
DataTables warning: Non-table node initialisation (DIV). For more information about this error, please see https://datatables.net/tn/2
```

A minimal example is

```
quarto --version
1.5.57
```

```
itables v2.1.5
```

```
---
title: "iTables with Caption and Pandas Styler"
format: html
---

```{python}
import numpy as np
import pandas as pd
from itables import init_notebook_mode

from itables.version import __version__

print(f"This is itables v{__version__}")
init_notebook_mode(all_interactive=True)

x = np.linspace(0, np.pi, 21)
df = pd.DataFrame({"sin": np.sin(x), "cos": np.cos(x)}, index=pd.Index(x, name="alpha"))

s = df.style

s.format("{:.3f}").format_index("{:.3f}")

s.set_caption("A Pandas Styler object").set_table_styles(
    [{"selector": "caption", "props": "caption-side: bottom; font-size:1em;"}]
)

```

The warning does not occur if the caption is not set.

**Comment by mwouts** [comment]
Hi @SvenKlaassen , thank you for the precise and helpful bug report! I have been able to reproduce and fix the problem in my dev environment.

May I ask you to give it a try as well? See the instructions at https://github.com/mwouts/itables/pull/318#issuecomment-2339183627. Thanks!

**Comment by SvenKlaassen** [comment]
Thank you for the very fast reply @mwouts! 
The fix also solves the issue for me.

**Comment by mwouts** [comment]
You're welcome! Actually I see that, while the change fixes the issue in Quarto, it introduces a very significant regression (e.g. itables stops working in all the other contexts!!). I'll have a look and keep you posted!

**Comment by SvenKlaassen** [comment]
I still works perfectly on the PR. 
Thanks again for the very fast update!
