### ISSUE TITLE
2 Problems with SearchPanes

### ISSUE THREAD

**Issue by tomnobelsAM** [mwouts/itables#328]
In this code , there are 2 problems : 
1. 'Header of the column is not shown without a reset_index()
2. Only the first column appears in the searchPanes although 3 are asked.

Can someone help me please ? Thanks

I tried the most recent version and version 2.0 of itables

import itables
from itables.sample_dfs import get_countries

df = get_countries(html=False)
# df.reset_index(inplace=True) with reset_index header 'region' is shown , without reset header is not shown

show(
    df,
    layout={"top1": "searchPanes"},
    searchPanes={"layout": "columns-3", "cascadePanes": True, "columns": [1, 2, 3]})

#only the first column is shown in the Panes

**Comment by mwouts** [comment]
Hey @tomnobelsAM , thanks for reaching out.

It's important to highlight that ITables is a wrapper for datatables.net. Some of the datatables extensions like searchpanes work better with simple headers - this explains what you observe with `.reset_index()`.

Re the second question about not having all the desired columns in the SearchPanes extension, an entry point is https://datatables.net/forums/discussion/72330/issue-with-searchpanes-not-showing-any-columns. The first answer works, e.g. you just need to add `"threshold":1` to the `searchPanes` dict as below:
```
import itables
from itables.sample_dfs import get_countries

df = get_countries(html=False)
df.reset_index(inplace=True)

itables.show(
    df,
    layout={"top1": "searchPanes"},
    searchPanes={
        "layout": "columns-3",
        "threshold": 1, # <=== include all the columns, even those which have a low uniqueness rate
        "cascadePanes": True,
        "columns": [1, 2, 3],
    },
)```

**Comment by tomnobelsAM** [comment]
Thanks Marc, this helped to solve my problem.   I thing is strange, when  a column has only one value.  De column is omitted and the other 2 are placed left and right ,in cause you selected 3 columns.  
I my case my column 0 was like that and the column 1 selector was left and the column 2 selector right.
