### ISSUE TITLE
searchbuilder gives wrong warning if column contains datetime

### ISSUE THREAD

**Issue by tomnobelsAM** [mwouts/itables#329]
When there is a datetime column (even after conversion to datetime with pandas) the searchbuilder always gives a warning that he needs a datetime and refuses to show the searchbuilder.

as object or datetime , I always get the warning

so  datetime in dataframe means no searchbuilder

Has someone a solution for this ?

Thanks a lot in advance

**Comment by mwouts** [comment]
Hello @tomnobelsAM , the issue description ressembles #288, which was fixed in version 2.1.5. Can you confirm that you are using the latest version of ITables?

**Comment by sidviny** [comment]
Hi,

I work together with Tom.

The version of iTables is 2.2.2

from our conda export: itables=2.2.2=pyh80e38bb_0

Yves VINDEVOGEL – Python Developer
DFE - ArcelorMittal
JF Kennedylaan 51, 9042 Gent, Belgium<https://urldefense.com/v3/__https:/www.google.com/maps/search/Kennedylaan*51,*9042*Gent,*Belgium?entry=gmail&source=g__;KysrKw!!AB_04_y_3-SRqw!9Q-LQ-y9853dsSluV7kw_x_jAO5vxBSX-ZAP3Vei0lLYzoWkCjnknsp7FGVb_TbaaxdGg49MqgW_SVYyVsHQ9CADxJh9Q8YJrW52nw$> (Office 1111-1215)
Mob +32 497 570896

**Comment by tomnobelsAM** [comment]
Hi,
The version where is went wrong is 2.0.0.
With the version 2.2.2 it works fine.

Thanks a lot for your answer, Marc

Best regards
Tom

Van: Yves Vindevogel ***@***.***>
Verzonden: woensdag 23 oktober 2024 9:28
Aan: mwouts/itables ***@***.***>
CC: Nobels, Tom ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mwouts/itables] searchbuilder gives wrong warning if column contains datetime (Issue #329)


***External email warning: This email originated outside the company. Please do not click links or open attachments unless you were expecting this communication.***

Hi,

I work together with Tom.

The version of iTables is 2.2.2

from our conda export: itables=2.2.2=pyh80e38bb_0

Yves VINDEVOGEL – Python Developer
DFE - ArcelorMittal
JF Kennedylaan 51, 9042 Gent, Belgium<https://urldefense.com/v3/__https:/www.google.com/maps/search/Kennedylaan*51,*9042*Gent,*Belgium?entry=gmail&source=g__;KysrKw!!AB_04_y_3-SRqw!9Q-LQ-y9853dsSluV7kw_x_jAO5vxBSX-ZAP3Vei0lLYzoWkCjnknsp7FGVb_TbaaxdGg49MqgW_SVYyVsHQ9CADxJh9Q8YJrW52nw$> (Office 1111-1215)
Mob +32 497 570896
