### ISSUE TITLE
Exported HTML File doesn't contain column filter when "footer" is chosen

### ISSUE THREAD

**Issue by lcorrigan** [mwouts/itables#331]
I'm using itables v2.2.2 in a Jupyter Notebook in VSCode.  

When I'm done running my notebook I export it using the VSCode Export To HTML command or via a cell where I call nbconvert to do it.

If the column_filters is set to "header", the filters are indeed found in the exported HTML file but they are not there if if I select "footer". I like footer more than header because the header replaces the column name with a "search for x" box, so I'd like to avoid switching to header if possible. 

Although it makes no difference if I call my options globally or doing show(), here is my current list of options I use:
```python
import itables.options
itables.options.buttons = ["pageLength", "copyHtml5", "csvHtml5", "colvis"]
itables.options.select = True
itables.options.colReorder = True
itables.options.maxBytes = "128KB"
itables.options.paging=True
itables.options.select=True
itables.options.lengthMenu=[10, 15, 20, 30, 50, 100]
itables.options.column_filters="footer"
itables.options.layout={"topEnd": None}
itables.options.search={"regex": True, "caseInsensitive": True}
itables.options.classes="display nowrap compact cell-border"
init_notebook_mode(all_interactive=True, connected=True)
```

As a side question, does anyone know if there is a setting to stop the column from being sorted when you type into the column search box? More just curious on that.

Thanks, and great package BTW.

**Comment by mwouts** [comment]
Hey @lcorrigan , thanks for reporting this!

I confirm that I can reproduce the issue. Looking at the generated HTML it looks like the Jupyter to HTML conversion moves the table footer outside of the table. I will move the footer with the header as this seems to fix the issue, and release v2.2.3 with the fix.

> As a side question, does anyone know if there is a setting to stop the column from being sorted when you type into the column search box? More just curious on that.

I could not reproduce that one - if you have an example that you can deploy on the web maybe you could ask on the datatables.net forums?
