### ISSUE TITLE
Several display in cell causes html export to bug

### ISSUE THREAD

**Issue by JulienBrn** [mwouts/itables#338]
I have been using itables with great success in Jupyter notebooks, however, a small bug seems to be occurring when exporting the notebooks to static html (which I regularly do): after the first call to display, all other cell outputs are not rendered (note that all is well rendered from within vscode). This happens both using the vscode export to html button or running nbconvert directly from the command line. I do not know whether this is a nbconvert bug or an itable bug, but since this problem seems to be specifically occurring with itables, I felt I should start here.

The test notenook has the following cells:

```python
import pandas as pd
import itables
itables.init_notebook_mode(all_interactive=True)
```
```python
df = pd.DataFrame([["some_data"]])
print("this will be rendered")
display(df)
print("this and the following table are not rendred")
display(df)
```
Image of the rendered html (on firefox)

![Screenshot from 2024-11-28 14-09-06](https://github.com/user-attachments/assets/16fed958-6573-4520-8879-20e0f27a75cf)

You will find the jupyter file and the converted html file in this archive.
[itables_bug.zip](https://github.com/user-attachments/files/17948450/itables_bug.zip)

**Comment by JulienBrn** [comment]
I have looked a bit at the generated html and the problem is that the two divs with class `jp-OutputArea-child` corresponding to the following code are not within the `jp-OutputArea jp-Cell-outputArea` div. Moving them within solves the problem.
```
print("this and the following table are not rendred")
display(df)
```

![Screenshot from 2024-12-04 14-39-03](https://github.com/user-attachments/assets/6fb95430-ab62-473f-93c8-346ed0a24e5c)

However, I do not know why these divs are misplaced. Perhaps some javascript in itables is moving them ?

**Comment by mwouts** [comment]
Thanks @JulienBrn for looking into this!

I have been able to address this issue by removing some divs elements within the table, see the attached PR - it was just about the loading message!

I am going to release ITables v2.2.4 which should not have this issue anymore.
