### ISSUE TITLE
FileNotFoundError: require_config.js

### ISSUE THREAD

**Issue by housezipmex** [mwouts/itables#48]
Hi
This is the first time I tried to use itables on Jypyter.
Got this error
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Anaconda3\\lib\\site-packages\\itables\\require_config.js'`
version 0.4.3

**Comment by mwouts** [comment]
Damned! You're right, I forgot to update `setup.py`. This will be fixed in `itables==0.4.4`.

**Comment by mwouts** [comment]
The new version is [being published](https://github.com/mwouts/itables/actions/runs/1676230132) on pip, thank you so much for reporting this!

**Comment by housezipmex** [comment]
Thank you
