### ISSUE TITLE
Column width were not right and strings were overlapping

### ISSUE THREAD

**Issue by orcahmlee** [mwouts/itables#5]
Thank you for working on this package.

I could successfully render the breast_cancer data frame on jupyter notebook and I could successfully convert data tables to static html.

However, after convert to static html, the column width were not right and the column names were overlapping to each other.

Here are my print screens.
![Screen Shot 2019-06-03 at 13 47 50](https://user-images.githubusercontent.com/26179752/58779297-1152a500-8608-11e9-97c8-3d4bdcad8176.png)

`Save Notebook Widget State`
![Screen Shot 2019-06-03 at 11 18 25](https://user-images.githubusercontent.com/26179752/58779298-1152a500-8608-11e9-8aba-48eca4a23e30.png)

`Download as HTML(.html)`
![Screen Shot 2019-06-03 at 11 18 35](https://user-images.githubusercontent.com/26179752/58779299-1152a500-8608-11e9-8341-2c00dc041b3e.png)

`It's gone`
![Screen Shot 2019-06-03 at 13 48 29](https://user-images.githubusercontent.com/26179752/58779301-1152a500-8608-11e9-95c2-4a704d3b92ef.png)

**Comment by mwouts** [comment]
Hello @orcahmlee , thanks for reporting this - this is an interesting testing case.
To some extend, this is related to #1 (with the difference that you see the issue only in the HTML file).

At the moment I do not think I will be able to work on this soon. Still I would be interested to hear why you would prefer to use itables/datatables rather than a more mainstream library like `gqrid`, `beakerx`, `ipyaggrid` or `ipysheet`?

**Comment by orcahmlee** [comment]
@mwouts well, I would like to convert my jupyter notebook to HTML as a report which likes RMarkdown does. I've tried using `qgrid` but it's still couldn't get interactive datatables after `nbconvert`. Meanwhile I've tried the other new package `jupyter-datatables`, I got the same result(https://github.com/CermakM/jupyter-datatables/issues/6).

**Comment by mwouts** [comment]
Interesting! Sure, while having a look at these tables I also found that HTML export was often an issue. 

Most of the implementations (not mine) use widgets, so you should make sure that you save the widget state. But I think you do that already, seeing your screenshots. So it might be that `qgrid` uses a _server side mode_, i.e. serves the data from the Python kernel, and does not store the table in the notebook... in which case the table cannot be exported to HTML. If we could find a table in which the user can choose between server mode and embedded data, that would be great!

**Comment by orcahmlee** [comment]
> Interesting! Sure, while having a look at these tables I also found that HTML export was often an issue.
> 
> Most of the implementations (not mine) use widgets, so you should make sure that you save the widget state. But I think you do that already, seeing your screenshots. So it might be that `qgrid` uses a _server side mode_, i.e. serves the data from the Python kernel, and does not store the table in the notebook... in which case the table cannot be exported to HTML. If we could find a table in which the user can choose between server mode and embedded data, that would be great!

WOW, thanks for your kindly explanation, I've been wondering this issues for a while(because I am a rookie programmer and haven't studied in computer science).

While I surveyed, some of solutions that  suggest me using [binder](https://mybinder.org/) to render the jupyter notebook. However, we have to show(or give) the report to our clients in some scenarios. It's difficult to teach(or require) the clients using [binder](https://mybinder.org/). The static HTML is best solution I found currently. Just I've seen in R Markdown.

**Comment by jinchenhougit** [comment]
Hi Marc,

Thank you for replying my email! I noticed that I have the exactly the same issue with @orcahmlee.

Wondering if any updates on this issue?

**Comment by mwouts** [comment]
> I noticed that I have the exactly the same issue with @orcahmlee.

Oh, interesting!

> Wondering if any updates on this issue?

Not yet, but I'll try to give it a look soon. I'll keep you posted.

**Comment by mwouts** [comment]
Hello @orcahmlee , @jinchenhougit , it seems that using a fixed width in `columnDefs` can solve this issue.

You can use it locally:
```python
from sklearn import datasets
import pandas as pd
breast_cancer = datasets.load_breast_cancer()
breast_cancer = pd.DataFrame(data=breast_cancer.data, columns=breast_cancer.feature_names)
```

```python
from itables import show
show(breast_cancer.head(3), columnDefs=[{'width':'100px', 'targets':"_all"}])
```

or globally
```python
import itables.options as opt
opt.columnDefs=[{'width':'100px', 'targets':"_all"}]
show(breast_cancer.head(3)
```

![image](https://user-images.githubusercontent.com/29915202/68183319-5eaeb600-ff9c-11e9-9826-8230bbfea15b.png)

See also the second column width example in the [README](https://mwouts.github.io/itables/#Column-width).
