### ISSUE TITLE
Support passing custom dt_args into DataTable() 

### ISSUE THREAD

**Issue by jklap** [mwouts/itables#52]
Currently it's hardcoded to only pass in "data" but would be create if that could be customized in some way

**Comment by mwouts** [comment]
Hi @jklap , well in the [template](https://github.com/mwouts/itables/blob/main/itables/datatables_template.html) the  `dt_args` are empty, but that is just a template. In practice we replace that with the arguments passed by the user:
https://github.com/mwouts/itables/blob/6a194090c010fcae44e184da06866cad665513a4/itables/javascript.py#L188-L190

That means that you can pass to the `show` function, or to `itables.options`, any argument that you wish to see in the `dt_args`.

Is that what you were looking for?

(Examples are available in the [README](https://mwouts.github.io/itables/))

**Comment by jklap** [comment]
Yep-- that looks great. Didn't realize the second arg passed to `show()` was passing directly to `DataTable()`. Thanks!

**Comment by mwouts** [comment]
Thanks @jklap . Also feel free to open a PR if you think we can state this more clearly in the README.
