### ISSUE TITLE
Refreshing the page breaks itables

### ISSUE THREAD

**Issue by neon-ninja** [mwouts/itables#6]
Steps to reproduce:

Open https://mybinder.org/v2/gh/mwouts/itables/master?filepath=README.md
Run the first cell
Refresh the page
Re-run the first cell

**Comment by mwouts** [comment]
Oh thanks @neon-ninja for reporting this. That's interesting. I'll have a look and see what I can do.

**Comment by mwouts** [comment]
The Binder example now works with `itables>=0.3.0` - sorry it took so long to fix that!

Please note that the initialization now works a bit differently - to display all the tables interactively, you should start your notebook with
```
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)
```
(anyway, if you use the previous import, a warning will remind you of the correct initialization)
