### ISSUE TITLE
Cell width fixed 41 characters

### ISSUE THREAD

**Issue by qrun** [mwouts/itables#61]
If you have more than 41 character text in a cell, 
the cells well not be adjusted to the longest text in the column or the text will not be displayed in two lines in the cell.
The cell will display the follwoing:
a123456789b123456789b123456789c123456789d...

Sample Values
a123456789b123456789b123456789c123456789d12,ZH,Africa Eastern and Southern,Aggregates,,Aggregates,Aggregates,,,

**Comment by mwouts** [comment]
Thank you @qrun for reporting this.
Could you please share a code snippet that reproduces the problem (with a screenshot if possible)?

Also, have you tried setting a custom [column width](https://mwouts.github.io/itables/advanced_parameters.html?highlight=width#column-width), or a custom [class](https://mwouts.github.io/itables/advanced_parameters.html?highlight=width#table-and-cell-style) on the table?

**Comment by mwouts** [comment]
Hello @qrun , I am wondering if we could not just delete the current fixed width at 70 pixels. Could you please try the following?
```
import itables.options as opt

del opt.columnDefs
```
and tell us whether the behavior without the fixed width correspond to what you're looking for?

NB: you could also edit your `itables/options.py` file and remove `columnsDefs` there, like in this [PR](https://github.com/mwouts/itables/pull/64/files).

**Comment by mwouts** [comment]
This should be solved in `itables==0.4.6` (please let me know if not)
