### ISSUE TITLE
Automatically adjust column width to length of strings in dataframe

### ISSUE THREAD

**Issue by Jonas231** [mwouts/itables#66]
Hello,
thank you for providing this nice package. 
I have the following issue:
I would like to display a table of a dataframe loaded from an excel table. The first 4 columns have strings which are rather short, while the 5th columns contains lengthier text. How can I adjust the columns' width individually or automatically in itables?
![grafik](https://user-images.githubusercontent.com/38330725/160080581-f90fe822-152b-4f3a-9df1-6826fa937d50.png)

Best regards,
Jonas

**Comment by Jonas231** [comment]
Hi,
I found this solution which works for me:
![grafik](https://user-images.githubusercontent.com/38330725/160093376-4343396c-70cb-4d0b-9e12-f85126391f86.png)
Regards,
Jonas

**Comment by mwouts** [comment]
Hi Jonas,

Thank you for your comments. Yes `datatables.net` let you adjust the column width individually.

Out of curiosity, what do you get if you remove overall the `width` in the `columnDefs`?

I am asking as I am thinking of removing the default value at 70 pixels, cf. #64, this seems to work for my use cases but I'd rather have a confirmation from other users before proceeding.

**Comment by mwouts** [comment]
I'll close this issue as I believe that the new behavior in `itables==0.4.6` (automatic column width by default) improves this use case. 

Also the [documentation](https://mwouts.github.io/itables/advanced_parameters.html#column-width) has been updated to give an example of width adjustment for selected columns, as in your screenshot above.
