### ISSUE TITLE
"Loading...", then maybe

### ISSUE THREAD

**Issue by jainraje** [mwouts/itables#75]
The guidance to solve this very weak and the "see our [require.config]" is broken. What am I suppose to do to resolve this??

thank-you!

**Comment by mwouts** [comment]
Thank you for noticing the broken link! Indeed it should be https://github.com/mwouts/itables/blob/main/itables/require_config.js

Can you share more details of how you use `itables`? Are you using Jupyter Notebook, Jupyter Lab, or yet another editor ? In which version ? Is your notebook "Trusted" ? Do you have access to the internet ?

**Comment by drnw** [comment]
I too get  `Loading... (need [help](https://mwouts.github.io/itables/troubleshooting.html)?)`. I use VS Code on Mac OS. In a session last week I somehow got past this. However, now rerunning my Jupyter Notebook itables is back to its bad behaviour :-(
<img width="411" alt="image" src="https://user-images.githubusercontent.com/24733582/173735437-c666113a-a573-4527-bfef-a4eb2c85267a.png">

Yes I am online. Visual Studio Code Version: 1.68.0

I think the notebook is trusted but I am not sure how to double check this.

**Comment by drnw** [comment]
Inspecting the Jupyter extension in VS Code I noticed "Reload required".

<img width="618" alt="image" src="https://user-images.githubusercontent.com/24733582/173736976-1e207f31-4375-4f4c-9ef8-f8a1e24fcdc3.png">

After clicking the Reload button the itable magically appeared in my Notebook cell output. However, cells would no longer run and a restart of VS Code was needed to restore normal service.

**Comment by drnw** [comment]
Unfortunately the behaviour is intermittent. Some notebooks still have the `Loading...` issue. Reinstalling the Jupyter extension and restarting VS Code has some success but this is a real pain :-(

**Comment by mwouts** [comment]
Hi @drnw , sorry to hear that... I think it would help if we could see the browser logs, but I have no idea how to see the logs for Javascript content in VS Code. This [SO question](https://stackoverflow.com/questions/70768787/javascript-in-vscode-jupyter-notebook-not-showing-output) has no answer, does anyone know how to get more debug information in this context?

**Comment by mwouts** [comment]
Hi @drnw , we have just published `itables==1.0.0` which introduces an offline mode - now you don't need to be online any more to see the interactive tables.

Would you mind to upgrade `itables` and let us know whether the new offline mode works better?

Note that the offline mode is the default, so you don't need to change anything in your notebooks, you just need to restart the kernel and re-run them.

**Comment by drnw** [comment]
@mwouts above you said

> the offline mode is the default, so you don't need to change anything in your notebooks

So my first try (which worked) was not to call `init_notebook_mode`. Please clarify if you can.

**Comment by mwouts** [comment]
Oh I see... Well I would expect users to call `init_notebook_mode` at the top of their notebook (cf. the [documentation](https://mwouts.github.io/itables)). 
That function now has an argument `connected` that defaults to `False` (except in Google Colab), so calling that function will activate the offline mode in VS Code.

If you don't call `init_notebook_mode` (or if you call it with `connected=True`) then the offline mode is not activated, see [the source code](https://github.com/mwouts/itables/blob/8f6569385d652bb1ef116d817270b840a74c4873/itables/javascript.py). So I don't see what makes it work offline in VS Code (but I just tested and I do agree with you that it does work when the wifi is down...)
