### ISSUE TITLE
Interactive tables fail to load when a notebook is reloaded in PyCharm

### ISSUE THREAD

**Issue by mwouts** [mwouts/itables#79]
When a notebook is reloaded in PyCharm, the interactive tables display "Loading ... (need help?)" but the tables never show up.
This affects `itables==1.0.0` (which introduces the offline mode).

Known workaround: call `init_notebook_mode` with `connected=True` to restore the connected mode which is not affected by this issue.

Please comment on this thread if you know how to
- Show browser logs in PyCharm
- Detect that the notebook is being opened in PyCharm (then we could change the default value for `connected` in that case)

**Comment by RealYHD** [comment]
I'm having this same issue with a JupyterLab version 3.5.2 instance created by a JupyterHub version 3.1.0. Using the `connected` parameter as described by @mwouts also works.
