### ISSUE TITLE
Support downsampling only rows, not columns?

### ISSUE THREAD

**Issue by ofir-reich** [mwouts/itables#84]
I find that downsampling rows makes a lot of sense, while downsampling columns almost always makes me rerun the line and downsample myself.
Is there a way to support this natively? I would argue that the default should be to downsample only rows and not columns, but even if it's not - it would be great if it's configurable somehow, so that I can make that be the behavior.

Thanks!

**Comment by mwouts** [comment]
For instance, the example in the docs, which was downsampled 500x7 to 250x3:
![image](https://user-images.githubusercontent.com/29915202/176778159-b58dac65-6d30-4a69-b686-5577383527eb.png)

Is now downsampled 500x7 to 178x7:
![image](https://user-images.githubusercontent.com/29915202/176778270-57247802-e92b-4f23-9bc5-d5b4aa62a560.png)

**Comment by mwouts** [comment]
Hi @ofir-reich , I think this is a good addition to the library, so I have integrated the PR and the new downsampling approach will  be available in `itables==1.1.2`.

**Comment by ofir-reich** [comment]
Wow, thanks! Didn't even get a chance to test it!
