### ISSUE TITLE
Add documentation link to GitHub About

### ISSUE THREAD

**Issue by AdamRJensen** [mwouts/itables#87]
I would like to propose that the URL to the documentation be added to the about section on GitHub (see example below). This is done for Numpy, Pandas, etc. and how I think a lot of people navigate their way to the documentation.

![image](https://user-images.githubusercontent.com/39184289/182537408-9c368d5d-b805-411e-8189-01bb3712ef0a.png)

**Comment by mwouts** [comment]
Thank you @AdamRJensen, yes that's a great idea - I've just added a link to https://mwouts.github.io/itables/ . Thank you for proposing this!
