### ISSUE TITLE
jQuery import

### ISSUE THREAD

**Issue by JanPalasek** [mwouts/itables#91]
Hi,

I try to integrate your awesome package into [Pretty Jupyter](https://github.com/JanPalasek/pretty-jupyter). I noticed that `itables` loads the jQuery without a possibility to overload this settings. This is a bit problematic for me because in the exported HTML file I use another jQuery, which is overwritten by this import. I hotfixed it with `jQuery.noConflict()` for now, however a better solution is needed.

Some possible solutions that occur to me:
- Allow to load not load jQuery. Here might be a problem with different IDEs (vscode,...) having or not having jQuery already imported.
- Load the jQuery only if there is none yet loaded.
- Avoid global variable $ and use your own named version. It might also be necessary to force this onto DataTables.

I would like also to ask if there is a reliable way to detect whether the jQuery was imported. I hacked some selector `($(".output_subarea.output_javascript")`, but i don't know if this will hold in future releases. Some IDd element would be nice, but I didn't find any.

**Comment by mwouts** [comment]
Hi @JanPalasek , thanks for reporting this. Could you please confirm which version of `itables` you use, and also if you use the connected or the offline mode?

In the latest release (1.1.3), in the connected mode (the default), we import jQuery in a script with type "module", cf. this code:
https://github.com/mwouts/itables/blob/30f2079e9d3df9f02143bc65247a21b382359504/itables/html/datatables_template_connected.html#L6-L8

At the moment we cannot import `jQuery` as an ES module but when `jQuery==4.0.0` becomes available we should be able to do so, and I expect this will allow us to get rid of the global variable `$`.

**Comment by JanPalasek** [comment]
Hello, thank you for such a quick answer. I also use jQuery==3.6.0.
It throws errors both with connected=True and False.
Here's the page it fails on.

[Playground.zip](https://github.com/mwouts/itables/files/9334141/Playground.zip)

This code on proper place fixes the issue (before the big <script> at the bototm). It just verifies that itables was used somewhere (and hence jquery was imported) and then drops its hold on $ variable.

```
<script type="text/javascript">
    if ($(".output_subarea.output_javascript").length > 0) {
      jQuery.noConflict(false);
    }
</script>
```

I think you could do something like this as well to release the $ variable. Although it's just a hypothesis, I'm not really a JS dev. For example:

```javascript
 import 'https://code.jquery.com/jquery-3.6.0.min.js'; 
 import dt from 'https://cdn.datatables.net/1.12.1/js/jquery.dataTables.mjs';
 // release $ variable 
 let itablesJQuery =  jQuery.noConflict(false);
 dt(itablesJQuery);
```

**Comment by JanPalasek** [comment]
I use last released version of itables, 1.1.3.

**Comment by mwouts** [comment]
Hi @JanPalasek , oh that's interesting. I would be happy to take a PR that implements this, especially as it seems that you're almost done with the connected mode.

How do you think we could do this for the offline mode? In that mode, jQuery is loaded at this line:
https://github.com/mwouts/itables/blob/30f2079e9d3df9f02143bc65247a21b382359504/itables/javascript.py#L80

**Comment by JanPalasek** [comment]
> 

Yes, I hope so. But both needs to be tested. It’s just my (un)educated guess. I’m no JS dev.

It will probably take a while before I get to the PR.

**Comment by mwouts** [comment]
Closing as `to_html_datatable` now has an `import_jquery` argument.
