### ISSUE TITLE
Documentation: readme

### ISSUE THREAD

**Issue by joseberlines** [mwouts/itables#93]
I suggest to add a couple of screenshots to the readme of the github page.
A pic is often worth a million words.

**Comment by mwouts** [comment]
Hi @joseberlines , yes sure that's a good idea. I have prepared this update:
https://github.com/mwouts/itables/tree/screenshots_in_readme

Do you think that's helpful / would you have added more screenshots?

**Comment by joseberlines** [comment]
Give some time to look at that and I will report back

**Comment by joseberlines** [comment]
Give some time to look at that and I will report back

**Comment by mwouts** [comment]
I have merged the PR. Thank you @joseberlines for suggesting this!
