### ISSUE TITLE
Editable table in the future?

### ISSUE THREAD

**Issue by joseberlines** [mwouts/itables#95]
Is there any intention to make the table editable? Not only displaying and filtering data but editing cells and add or modify content of cells.

**Comment by mwouts** [comment]
Hi @joseberlines , personnally I don't have plans to make interative tables editables.

Two remarks on this:
1. https://datatables.net offers a (non free) plugin for making tables editables, which is https://editor.datatables.net/, but last time I looked at this I think I saw that [DT](https://github.com/rstudio/DT) uses another approach (i.e. sounds like they have coded the editor themselves).
2. In addition to making the table editable in the web page (with either one of the above), there is a second challenge which is how to get the updated table back in Python.

**Comment by joseberlines** [comment]
I can't not comment on the dificulties of implementing such an editable table. I can only say that there is still the need in the jupyter lab community to have an easy to used editable and readable table. There are indeed several possibilities (ipydatagrid, ipyvuetify (on top of vue), mito (pay version) etc but none so far offers an easy to use editable table. I ammjust saying this, as info, don't take this as a request. Oftentimes I have the feeling that people forget how much that would enable in jupyter lab.

**Comment by mwouts** [comment]
Yes, thank @joseberlines , sure I agree! I just quote the above if someone would like to consider addressing this issue.

**Comment by mwouts** [comment]
Closing as it has been a while + I don't have plans to implement edits for the foreseeable future.
