### ISSUE TITLE
Numeric > search 

### ISSUE THREAD

**Issue by beebeed** [mwouts/itables#97]
Hi @joseberlines,

Great work, simple and effective! 

I have two requests (happy to work on them)…
1) I was wondering if it would be possible/easy to implement regex search for numeric? It “great than x”, “less than y” etc? 

2) is it possible to color each cell as a function of it values heat map to highlight extremes.

Thanks again for all your work.

**Comment by mwouts** [comment]
Hi @beebeed , thank you for your comments & questions!

> is it possible to color each cell as a function of it values heat map to highlight extremes?

Yes you can do this, although you need to do that in Javascript. See for instance this [example](https://mwouts.github.io/itables/advanced_parameters.html#advanced-cell-formatting-with-js-callbacks)

> I was wondering if it would be possible/easy to implement regex search for numeric? It “great than x”, “less than y” etc?

Numeric values are represented as such when passed to https://datatables.net, so you won't be able to use a regex search. I think it should be doable to have a sliding selection for the rows between min/max values, like [DT](https://rstudio.github.io/DT/) have, but ATM I can't find a reference for this (you'd have to explore the https://datatables.net website and forum to find out)

**Comment by mwouts** [comment]
There is another issue with more inputs at #231 - but I don't have immediate plans to address this.
